/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * * `p` - pending * `s` - success * `c` - cancelled
 * @export
 * @enum {string}
 */
export enum BillStatusChoice {
  P = "p",
  S = "s",
  C = "c",
}
