/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from "./organization";
import { TicketType } from "./ticket-type";
/**
 *
 *
 * @export
 * @interface Event
 */
export interface Event {
  /**
   * @type {string}
   * @memberof Event
   */
  public_id: string;

  /**
   * @type {string}
   * @memberof Event
   */
  title: string;

  /**
   * @type {string}
   * @memberof Event
   */
  description: string;

  /**
   * @type {Organization}
   * @memberof Event
   */
  organization: Organization;

  /**
   * @type {Array<TicketType>}
   * @memberof Event
   */
  ticket_types: Array<TicketType>;

  /**
   * @type {string}
   * @memberof Event
   */
  image?: string | null;

  /**
   * @type {number}
   * @memberof Event
   */
  category?: number | null;

  /**
   * @type {Date}
   * @memberof Event
   */
  start_date: Date;

  /**
   * @type {Date}
   * @memberof Event
   */
  end_date: Date;

  /**
   * @type {string}
   * @memberof Event
   */
  location?: string | null;

  /**
   * @type {number}
   * @memberof Event
   */
  max_participants: number;

  /**
   * @type {boolean}
   * @memberof Event
   */
  is_active?: boolean;

  /**
   * @type {Date}
   * @memberof Event
   */
  created_at: Date;

  /**
   * @type {Date}
   * @memberof Event
   */
  updated_at: Date;
}
