/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketType } from "./ticket-type";
/**
 *
 *
 * @export
 * @interface EventCreate
 */
export interface EventCreate {
  /**
   * @type {string}
   * @memberof EventCreate
   */
  title: string;

<<<<<<< HEAD
    /**
     * @type {string}
     * @memberof EventCreate
     */
    public_id?: string;

    /**
     * @type {string}
     * @memberof EventCreate
     */
    title: string;
=======
  /**
   * @type {string}
   * @memberof EventCreate
   */
  description: string;
>>>>>>> ba26cb3 (chore: format code with Prettier)

  /**
   * @type {number}
   * @memberof EventCreate
   */
  organization: number;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  image?: string | null;

  /**
   * @type {number}
   * @memberof EventCreate
   */
  category?: number | null;

  /**
   * @type {Date}
   * @memberof EventCreate
   */
  start_date: Date;

  /**
   * @type {Date}
   * @memberof EventCreate
   */
  end_date: Date;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  location: string;

<<<<<<< HEAD
    /**
     * @type {string}
     * @memberof EventCreate
     */
    location?: string | null;

    /**
     * @type {Array<TicketType>}
     * @memberof EventCreate
     */
    ticket_types: Array<TicketType>;
=======
  /**
   * @type {Array<TicketType>}
   * @memberof EventCreate
   */
  ticket_types: Array<TicketType>;
>>>>>>> ba26cb3 (chore: format code with Prettier)
}
