/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketType } from "./ticket-type";
/**
 *
 *
 * @export
 * @interface EventCreate
 */
export interface EventCreate {
  /**
   * @type {string}
   * @memberof EventCreate
   */
  public_id: string;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  title: string;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  description: string;

  /**
   * @type {number}
   * @memberof EventCreate
   */
  organization: number;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  image?: string | null;

  /**
   * @type {number}
   * @memberof EventCreate
   */
  category?: number | null;

  /**
   * @type {Date}
   * @memberof EventCreate
   */
  start_date: Date;

  /**
   * @type {Date}
   * @memberof EventCreate
   */
  end_date: Date;

  /**
   * @type {string}
   * @memberof EventCreate
   */
  location?: string | null;

  /**
   * @type {Array<TicketType>}
   * @memberof EventCreate
   */
  ticket_types: Array<TicketType>;
}
