/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
  /**
   * Success message
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  message?: string;
}
