/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse4001
 */
export interface InlineResponse4001 {

    /**
     * @type {{ [key: string]: Array<string>; }}
     * @memberof InlineResponse4001
     */
    errors?: { [key: string]: Array<string>; };
}
