/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
  /**
   * Error message
   *
   * @type {string}
   * @memberof InlineResponse400
   */
  error?: string;
}
