/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse4001
 */
export interface InlineResponse4001 {

    /**
     * Error message
     *
     * @type {string}
     * @memberof InlineResponse4001
     */
    error?: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof InlineResponse4001
     */
    errors?: { [key: string]: string; };
}
