/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface News
 */
export interface News {
  /**
   * @type {number}
   * @memberof News
   */
  id?: number;

  /**
   * @type {string}
   * @memberof News
   */
  title: string;

  /**
   * @type {string}
   * @memberof News
   */
  slug?: string;

  /**
   * @type {string}
   * @memberof News
   */
  content: string;

  /**
   * @type {Date}
   * @memberof News
   */
  created_at?: Date;
}
