/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface News
 */
<<<<<<< HEAD:models/news.ts
export interface News {

    /**
     * @type {number}
     * @memberof News
     */
    id?: number;

    /**
     * @type {string}
     * @memberof News
     */
    title: string;

    /**
     * @type {string}
     * @memberof News
     */
    slug?: string;

    /**
     * @type {string}
     * @memberof News
     */
    content: string;

    /**
     * @type {Date}
     * @memberof News
     */
    created_at?: Date;
=======
export interface User {
  /**
   * @type {number}
   * @memberof User
   */
  id?: number;

  /**
   * @type {string}
   * @memberof User
   */
  email: string;

  /**
   * @type {string}
   * @memberof User
   */
  first_name?: string;

  /**
   * @type {string}
   * @memberof User
   */
  last_name?: string;

  /**
   * @type {Array<number>}
   * @memberof User
   */
  organizations: Array<number>;
>>>>>>> ba26cb3 (chore: format code with Prettier):models/user.ts
}
