/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface News
 */
export interface News {
  /**
   * @type {number}
   * @memberof News
   */
  id: number;

  /**
   * @type {string}
   * @memberof News
   */
  title: string;

  /**
   * @type {string}
   * @memberof News
   */
  slug?: string;

  /**
   * @type {string}
   * @memberof News
   */
  content: string;

  /**
   * @type {Date}
   * @memberof News
   */
  created_at: Date;
}
