/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
* 
*
* @export
* @interface Organization
*/
export interface Organization {
  /**
   * @type {number}
   * @memberof Organization
   */
  id?: number;

  /**
   * @type {string}
   * @memberof Organization
   */
  public_id?: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  description?: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  username: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  image?: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  description?: string;

  /**
   * @type {User}
   * @memberof Organization
   */
  owner?: User;

  /**
   * @type {string}
   * @memberof Organization
   */
  address?: string | null;

  /**
   * @type {string}
   * @memberof Organization
   */
  website?: string | null;
}
