/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrganizationCreate
 */
export interface OrganizationCreate {

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    name: string;

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    username: string;

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    description?: string;

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof OrganizationCreate
     */
    website?: string | null;
}
