/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface OrganizationCreate
 */
export interface OrganizationCreate {
  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  name: string;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  username: string;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  logo?: string;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  description?: string;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  email?: string | null;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  address?: string | null;

  /**
   * @type {string}
   * @memberof OrganizationCreate
   */
  website?: string | null;
}
