/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Organization
 */

import type { SocialLinks } from "./social-links";

export interface Organization {
  /**
   * @type {string}
   * @memberof Organization
   */
  public_id: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  name: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  username: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  logo?: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  description?: string;

  /**
   * @type {string}
   * @memberof Organization
   */
  email?: string | null;

  /**
   * @type {string}
   * @memberof Organization
   */
  address?: string | null;

  /**
   * @type {string}
   * @memberof Organization
   */
  website?: string | null;

  /**
   * @type {number}
   * @memberof Organization
   */
  event_count: number;

  /**
   * @type {Array<SocialLinks>}
   * @memberof Organization
   */

  social_links: SocialLinks[];
}
