/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Ticket } from "./ticket";
/**
 *
 *
 * @export
 * @interface PaginatedTicketList
 */
export interface PaginatedTicketList {
  /**
   * @type {number}
   * @memberof PaginatedTicketList
   * @example 123
   */
  count: number;

  /**
   * @type {string}
   * @memberof PaginatedTicketList
   * @example http://api.example.org/accounts/?page=4
   */
  next?: string | null;

  /**
   * @type {string}
   * @memberof PaginatedTicketList
   * @example http://api.example.org/accounts/?page=2
   */
  previous?: string | null;

  /**
   * @type {Array<Ticket>}
   * @memberof PaginatedTicketList
   */
  results: Array<Ticket>;
}
