/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PasswordReset
 */
export interface PasswordReset {
  /**
   * Password reset token send by email
   *
   * @type {string}
   * @memberof PasswordReset
   */
  token: string;

  /**
   * @type {string}
   * @memberof PasswordReset
   */
  password: string;
}
