/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PasswordResetRequest
 */
export interface PasswordResetRequest {

    /**
     * The email address of the user requesting a password reset
     *
     * @type {string}
     * @memberof PasswordResetRequest
     */
    email: string;
}
