/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketStatusChoice } from './ticket-status-choice';
import { TicketTransactionSerializerPublic } from './ticket-transaction-serializer-public';
import { TicketType } from './ticket-type';
 /**
 * 
 *
 * @export
 * @interface PatchedTicket
 */
export interface PatchedTicket {

    /**
     * @type {string}
     * @memberof PatchedTicket
     */
    public_id?: string;

    /**
     * @type {TicketType}
     * @memberof PatchedTicket
     */
    ticket_type?: TicketType;

    /**
     * @type {TicketStatusChoice}
     * @memberof PatchedTicket
     */
    status?: TicketStatusChoice;

    /**
     * @type {number}
     * @memberof PatchedTicket
     */
    ticket_number?: number;

    /**
     * @type {string}
     * @memberof PatchedTicket
     */
    notes?: string;

    /**
     * @type {Date}
     * @memberof PatchedTicket
     */
    created_at?: Date;

    /**
     * @type {Date}
     * @memberof PatchedTicket
     */
    updated_at?: Date;

    /**
     * @type {TicketTransactionSerializerPublic}
     * @memberof PatchedTicket
     */
    transactions?: TicketTransactionSerializerPublic;
}
