/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
import { TicketType } from './ticket-type';
 /**
 * 
 *
 * @export
 * @interface PatchedEvent
 */
export interface PatchedEvent {

    /**
     * @type {string}
     * @memberof PatchedEvent
     */
    public_id?: string;

    /**
     * @type {string}
     * @memberof PatchedEvent
     */
    title?: string;

    /**
     * @type {string}
     * @memberof PatchedEvent
     */
    description?: string;

    /**
     * @type {Organization}
     * @memberof PatchedEvent
     */
    organization?: Organization;

    /**
     * @type {Array<TicketType>}
     * @memberof PatchedEvent
     */
    ticket_types?: Array<TicketType>;

    /**
     * @type {string}
     * @memberof PatchedEvent
     */
    image?: string | null;

    /**
     * @type {number}
     * @memberof PatchedEvent
     */
    category?: number | null;

    /**
     * @type {Date}
     * @memberof PatchedEvent
     */
    start_date?: Date;

    /**
     * @type {Date}
     * @memberof PatchedEvent
     */
    end_date?: Date;

    /**
     * @type {string}
     * @memberof PatchedEvent
     */
    location?: string | null;

    /**
     * @type {number}
     * @memberof PatchedEvent
     */
    max_participants?: number;

    /**
     * @type {boolean}
     * @memberof PatchedEvent
     */
    is_active?: boolean;

    /**
     * @type {Date}
     * @memberof PatchedEvent
     */
    created_at?: Date;

    /**
     * @type {Date}
     * @memberof PatchedEvent
     */
    updated_at?: Date;
}
