/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PatchedSpeaker
 */
export interface PatchedSpeaker {
  /**
   * @type {string}
   * @memberof PatchedSpeaker
   */
  public_id?: string;

  /**
   * @type {string}
   * @memberof PatchedSpeaker
   */
  name?: string;

  /**
   * @type {string}
   * @memberof PatchedSpeaker
   */
  image?: string | null;

  /**
   * @type {Date}
   * @memberof PatchedSpeaker
   */
  created_at?: Date;

  /**
   * @type {Date}
   * @memberof PatchedSpeaker
   */
  updated_at?: Date;
}
