/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Speaker
 */
export interface Speaker {
  /**
   * @type {string}
   * @memberof Speaker
   */
  public_id?: string;

  /**
   * @type {string}
   * @memberof Speaker
   */
  name: string;

  /**
   * @type {string}
   * @memberof Speaker
   */
  image?: string | null;

  /**
   * @type {Date}
   * @memberof Speaker
   */
  created_at?: Date;

  /**
   * @type {Date}
   * @memberof Speaker
   */
  updated_at?: Date;
}
