/* tslint:disable */

/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TicketType
 */
export interface TicketType {
  /**
   * @type {string}
   * @memberof TicketType
   */
  public_id: string;

  /**
   * @type {string}
   * @memberof TicketType
   */
  title: string;

  /**
   * @type {string}
   * @memberof TicketType
   */
  description?: string;

  /**
   * @type {number}
   * @memberof TicketType
   */
  max_participants?: number | null;

  /**
   * @type {number}
   * @memberof TicketType
   */
  price: number;
}
