/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TicketType
 */
export interface TicketType {
  /**
   * @type {number}
   * @memberof TicketType
   */
  id?: number;

<<<<<<< HEAD
    /**
     * @type {string}
     * @memberof TicketType
     */
    public_id?: string;
=======
  /**
   * @type {string}
   * @memberof TicketType
   */
  title: string;
>>>>>>> ba26cb3 (chore: format code with Prettier)

  /**
   * @type {string}
   * @memberof TicketType
   */
  description?: string;

  /**
   * @type {number}
   * @memberof TicketType
   */
  max_participants?: number | null;

  /**
   * @type {number}
   * @memberof TicketType
   */
  price: number;
}
