/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TicketsResponseDataSerialize
 */
export interface TicketsResponseDataSerialize {
  /**
   * @type {string}
   * @memberof TicketsResponseDataSerialize
   */
  ticket_type_public_id: string;

  /**
   * @type {Array<string>}
   * @memberof TicketsResponseDataSerialize
   */
  ticket_public_ids: Array<string>;
}
