/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketStatusChoice } from "./ticket-status-choice";
import { TicketTransactionSerializerPublic } from "./ticket-transaction-serializer-public";
import { TicketType } from "./ticket-type";
/**
 *
 *
 * @export
 * @interface Ticket
 */
export interface Ticket {
  /**
   * @type {string}
   * @memberof Ticket
   */
  public_id: string;

  /**
   * @type {TicketType}
   * @memberof Ticket
   */
  ticket_type: TicketType;

  /**
   * @type {TicketStatusChoice}
   * @memberof Ticket
   */
  status?: TicketStatusChoice;

  /**
   * @type {number}
   * @memberof Ticket
   */
  ticket_number: number;

  /**
   * @type {string}
   * @memberof Ticket
   */
  notes?: string;

  /**
   * @type {Date}
   * @memberof Ticket
   */
  created_at: Date;

  /**
   * @type {Date}
   * @memberof Ticket
   */
  updated_at: Date;

  /**
   * @type {TicketTransactionSerializerPublic}
   * @memberof Ticket
   */
  transactions: TicketTransactionSerializerPublic;
}
