/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BillStatusChoice } from './bill-status-choice';
 /**
 * 
 *
 * @export
 * @interface TicketTransaction
 */
export interface TicketTransaction {

    /**
     * @type {string}
     * @memberof TicketTransaction
     */
    public_id: string;

    /**
     * @type {string}
     * @memberof TicketTransaction
     */
    amount: string;

    /**
     * @type {string}
     * @memberof TicketTransaction
     */
    authority: string | null;

    /**
     * @type {BillStatusChoice}
     * @memberof TicketTransaction
     */
    status: BillStatusChoice;

    /**
     * @type {Date}
     * @memberof TicketTransaction
     */
    created_at: Date;

    /**
     * @type {string}
     * @memberof TicketTransaction
     */
    transaction_id: string | null;

    /**
     * @type {Date}
     * @memberof TicketTransaction
     */
    paid_at: Date | null;
}
