/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TicketsResponseDataSerialize } from './tickets-response-data-serialize';
 /**
 * 
 *
 * @export
 * @interface TicketCreateResponse
 */
export interface TicketCreateResponse {

    /**
     * @type {Array<TicketsResponseDataSerialize>}
     * @memberof TicketCreateResponse
     */
    ticket_data: Array<TicketsResponseDataSerialize>;

    /**
     * @type {string}
     * @memberof TicketCreateResponse
     */
    transaction_public_id: string;
}
