/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TicketCreate
 */
export interface TicketCreate {

    /**
     * @type {number}
     * @memberof TicketCreate
     */
    ticket_type: number;

    /**
     * @type {string}
     * @memberof TicketCreate
     */
    notes?: string;
}
