/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BillStatusChoice } from "./bill-status-choice";
/**
 *
 *
 * @export
 * @interface TicketTransactionSerializerPublic
 */
export interface TicketTransactionSerializerPublic {
  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  public_id: string;

  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  amount: string;

  /**
   * @type {BillStatusChoice}
   * @memberof TicketTransactionSerializerPublic
   */
  status: BillStatusChoice;

  /**
   * @type {Date}
   * @memberof TicketTransactionSerializerPublic
   */
  created_at: Date;

  /**
   * @type {Date}
   * @memberof TicketTransactionSerializerPublic
   */
  paid_at: Date | null;
}
