/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TicketTransactionSerializerPublic
 */
export interface TicketTransactionSerializerPublic {
  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  public_id?: string;

  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  amount?: string;

  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  currency?: TicketTransactionSerializerPublicCurrencyEnum;

  /**
   * @type {string}
   * @memberof TicketTransactionSerializerPublic
   */
  status?: TicketTransactionSerializerPublicStatusEnum;

  /**
   * @type {Date}
   * @memberof TicketTransactionSerializerPublic
   */
  created_at?: Date;

  /**
   * @type {Date}
   * @memberof TicketTransactionSerializerPublic
   */
  paid_at?: Date | null;
}

/**
 * @export
 * @enum {string}
 */
export enum TicketTransactionSerializerPublicCurrencyEnum {
  IRR = "IRR",
  IRT = "IRT",
}
/**
 * @export
 * @enum {string}
 */
export enum TicketTransactionSerializerPublicStatusEnum {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
}
