/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TokenObtainPair
 */
export interface TokenObtainPair {

    /**
     * @type {string}
     * @memberof TokenObtainPair
     */
    email: string;

    /**
     * @type {string}
     * @memberof TokenObtainPair
     */
    password: string;

    /**
     * @type {string}
     * @memberof TokenObtainPair
     */
    access: string;

    /**
     * @type {string}
     * @memberof TokenObtainPair
     */
    refresh: string;
}
