/* tslint:disable */
/* eslint-disable */
/**
 * Neshast API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
 /**
 * 
 *
 * @export
 * @interface UserME
 */
export interface UserME {

    /**
     * @type {string}
     * @memberof UserME
     */
    public_id: string;

    /**
     * @type {string}
     * @memberof UserME
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserME
     */
    first_name?: string;

    /**
     * @type {string}
     * @memberof UserME
     */
    last_name?: string;

    /**
     * @type {string}
     * @memberof UserME
     */
    image?: string;

    /**
     * @type {Array<Organization>}
     * @memberof UserME
     */
    organizations: Array<Organization>;
}
