/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from "./organization";
/**
 *
 *
 * @export
 * @interface UserME
 */
export interface UserME {
  /**
   * @type {number}
   * @memberof UserME
   */
  id?: number;

<<<<<<< HEAD
    /**
     * @type {string}
     * @memberof UserME
     */
    public_id?: string;
=======
  /**
   * @type {string}
   * @memberof UserME
   */
  email: string;
>>>>>>> ba26cb3 (chore: format code with Prettier)

  /**
   * @type {string}
   * @memberof UserME
   */
  first_name?: string;

  /**
   * @type {string}
   * @memberof UserME
   */
  last_name?: string;

<<<<<<< HEAD
    /**
     * @type {string}
     * @memberof UserME
     */
    last_name?: string;

    /**
     * @type {string}
     * @memberof UserME
     */
    image?: string;

    /**
     * @type {Array<Organization>}
     * @memberof UserME
     */
    organizations?: Array<Organization>;
=======
  /**
   * @type {Array<Organization>}
   * @memberof UserME
   */
  organizations?: Array<Organization>;
>>>>>>> ba26cb3 (chore: format code with Prettier)
}
